.travis.yml
katana/native/settings/settings.py
warrior/Actions/SnmpActions/common_snmp_actions.py
warrior/Framework/Utils/xml_Utils.py
wftests/ci/custom_rules.py
wftests/ci/pylint_checker.py

instead of simple text matching, support regex using the re library in python

WAR-1792 support regex in snmp verify keyword

---

katana/utils/navigator_util.py
warrior/Warrior

Detail is explain in internal jira ticket

WAR-1770 Enhance Navigator utils to always return absolute path for dir

---

warrior/WarriorCore/Classes/testcase_utils_class.py

Details and logs are attached in the JIRA: WAR-1358

WAR-1812: print_warning creates two print 1. -W- "Warning 2. -I- Information

---

warrior/WarriorCore/testsuite_driver.py

Details are updated in the ticket: WAR-1381

WAR-1833: Not getting executed for y number of systems specified in ID file (when ID is passed using CLI command)

---

.travis.yml
warrior/Actions/SeleniumActions/browser_actions.py
warrior/Framework/ClassUtils/WSelenium/browser_mgmt.py

Details are provided in the PR for the ticket: WAR-1813.
**Note:**
Adding geckodriver support  for firefox versions > 47 with selenium V3 in .travis.yml

WAR-1865: Selenium: _make_browser() function got multiple values for keyword argument 'profile_dir'

---

warhorn/default_config.xml
warhorn/source/data.xml
warhorn/source/utils.py

1. Added pycryptodome dependency in config file.
2. Added user interactive pycryptodome installation in data file
3. Changed get_dict_with_versions function by adding pycryptodome 3.6.1 version

WAR-1919 Warhorn related changes for pycryptodome support

---

warrior/WarriorCore/Classes/katana_interface_class.py
warrior/WarriorCore/Classes/kw_driver_class.py
warrior/WarriorCore/exec_type_driver.py
wftests/ci/pylint.sh

Have a typo in Travis script, only happen in py3 repo

WAR-1796 Documentation and travis change

---

warrior/Framework/Utils/data_Utils.py

Details are provided in the ticket WAR-1116

WAR-1940: Remove 'cse script execution' option from warriorframework repo

---

warrior/Actions/GnmiActions/__init__.py
warrior/Actions/GnmiActions/gnmi_actions.py
warrior/Framework/ClassUtils/gnmi_utils_class.py
warrior/Framework/Utils/data_Utils.py
warrior/ProductDrivers/gnmi_driver.py
wftests/warrior_tests/config_files/selenium_func_tests/ec_verify_presence_of_elements.json
wftests/warrior_tests/config_files/selenium_func_tests/ec_warrior_selenium_Config.json

Py3 request for gNMI interface support.
Details are available in WAR-1759

WAR-1927: gNMI interface support from warrior

---

.travis.yml
katana/native/microservice_store/admin.py
katana/native/microservice_store/apps.py
katana/native/microservice_store/models.py
katana/native/microservice_store/static/microservice_store/css/microservice_store.css
katana/native/microservice_store/static/microservice_store/js/microservice_store.js
katana/native/microservice_store/templates/microservice_store/docker.html
katana/native/microservice_store/templates/microservice_store/host.html
katana/native/microservice_store/templates/microservice_store/index.html
katana/native/microservice_store/templates/microservice_store/kubernetes.html
katana/native/microservice_store/templates/microservice_store/registry.html
katana/native/microservice_store/templates/xml_templates/VC_microservices_registry_operations_template.xml
katana/native/microservice_store/templates/xml_templates/WDF_microservices_host_system_data_template.xml
katana/native/microservice_store/tests.py
katana/native/microservice_store/urls.py
katana/native/microservice_store/views.py
katana/native/microservice_store/wf_config.json
katana/static/oss/js/jquery-resizable.js
katana/utils/command_options_utils.py
katana/wui/core/templates/core/html_head.html
katana/wui/settings.py
katana/wui/urls.py
warrior/plugins/microservice_store_plugin/pluginspace/config_files/TD_microservices_registry_operations.xml
warrior/plugins/microservice_store_plugin/pluginspace/config_files/VC_microservices_registry_operations.xml
warrior/plugins/microservice_store_plugin/pluginspace/data/WDF_microservices_host_system_data.xml
warrior/plugins/microservice_store_plugin/pluginspace/suites/TS_microservices_host_operations.xml
warrior/plugins/microservice_store_plugin/pluginspace/testcases/TC_microservices_host_docker_operations.xml
warrior/plugins/microservice_store_plugin/pluginspace/testcases/TC_microservices_host_kubernetes_operations.xml

WAR-1947, WAR-1944 
Basic functionality of MicroService app for running Docker images through SSH.

WAR-1947/1944: Microservice

---

.travis.yml
warrior/WarriorCore/Classes/iterative_testsuite_class.py
warrior/WarriorCore/Classes/junit_class.py
warrior/WarriorCore/parallel_testcase_driver.py
warrior/WarriorCore/sequential_testcase_driver.py
warrior/WarriorCore/sequential_testsuite_driver.py
wftests/warrior_tests/projects/pj_framework_tests.xml
wftests/warrior_tests/projects/selenium_project.xml
wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_iter_par.xml
wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_iter_seq.xml
wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_parallel.xml
wftests/warrior_tests/suites/framework_tests/invalid_path_tests/ts_sequential.xml

Details are provided in WAR-1828.

WAR-1939: Testsuite end result printed as PASS eventhough the testcase in that suite is not in provided path

---

wftests/warrior_tests/projects/pj_runmode_retry_at_suite_level_at_project_file.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_ruf_at_ts_global_level_with_status_expected.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_ruf_at_ts_global_level_with_status_last_instance.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_ruf_verify_at_ts_global_level_with_status_expected.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_rup_at_ts_global_level_with_status_expected.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_rup_at_ts_global_level_with_status_last_instance.xml
wftests/warrior_tests/suites/framework_tests/runmode_tests/ts_runmode_rup_verify_at_ts_global_level_with_status_expected.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_ruf_at_tc_global_level_with_status_expected.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_ruf_at_tc_global_level_with_status_last_instance.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_ruf_verify_at_ts_global_level_with_status_expected.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_rup_at_tc_global_level_with_status_expected.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_rup_at_tc_global_level_with_status_last_instance.xml
wftests/warrior_tests/testcases/framework_tests/runmode_tests/tc_runmode_rup_verify_at_ts_global_level_with_status_expected.xml

Attached the logs in jira .
The respective py2 ticket for current ticket is : war-2004

war-2027(Add tests for runmode 'status' attribute support in Suite Details section)

---

katana/native/settings/static/settings/js/settings.js
katana/native/settings/templates/settings/index.html
katana/native/settings/templates/settings/secret.html
warrior/Tools/admin/secret.key

Encryption settings sub-app works again

WAR-1926: Encryption settings sub app should change to support encryption module, if any changes are needed in py_3 repo

---

warrior/WarriorCore/sequential_testcase_driver.py
wftests/warrior_tests/projects/pj_framework_tests.xml
wftests/warrior_tests/suites/framework_tests/on_error_goto/ts_with_on_error_goto_sc1.xml
wftests/warrior_tests/suites/framework_tests/on_error_goto/ts_with_on_error_goto_sc2.xml
wftests/warrior_tests/testcases/framework_tests/on_error_goto/tc_on_error_goto_sc1.xml
wftests/warrior_tests/testcases/framework_tests/on_error_goto/tc_on_error_goto_sc2.xml

-Attached pass logs in Jira ticket.

WAR-2064: The onError_action does not work when implemented in Test Suite

---

warrior/Framework/ClassUtils/gnmi_utils_class.py

-Attached pass logs in Jira ticket.

fix for war-2088(gnmi keywords passes even when the command given fails)

---

katana/wui/core/templates/core/site_settings.html
katana/wui/core/views.py

Adds a "Save and Restart" button: 
Also adds a "Refresh" button at the top:

WAR-2094 LDAP: Needs a restart on LDAP settings change if running on uwsgi

---

warrior/WarriorCore/Classes/warmock_class.py

add log option in verify_cmd_response argument.

WAR-2141 - update warmock_class.py

---

warrior/Framework/ClassUtils/rest_utils_class.py
wftests/warrior_tests/config_files/rest_functional_tests/verify_api_response_with_repo_variable.json
wftests/warrior_tests/data/rest_functional_tests/rest_verify_response_data.xml
wftests/warrior_tests/suites/rest_functional_tests/rest_json_test_Suite.xml
wftests/warrior_tests/testcases/rest_functional_tests/tc_not_presented_repo_variable_substitution_in_verify_response.xml
wftests/warrior_tests/testcases/rest_functional_tests/tc_repo_variable_substitution_in_verify_response.xml

Feature/war 2156(Adding support for REPO substitutions as well in verify response json)

---

warrior/Framework/ClassUtils/WNetwork/warrior_cli_class.py

fix for war-1955(No need to wait for sleep timer during mockrun)

---

setup.py
warrior/Actions/SnmpActions/common_snmp_actions.py
warrior/Framework/Utils/snmp_utils.py
wftests/warrior_tests/suites/selenium_func_tests/gen_test_suite.xml

fix for war-2195(Need to add keyword (clear_received_traps) in common_snmp_actions)

---

katana/utils/file_utils.py

A new function is added in katana file utils that takes filepath and type as an argument, and returns HttpResponse with file attachment.

WAR-1945: File download functionality in katana file_utils 

---

katana/wui/config.ini
katana/wui/core/core_utils/core_settings.py
katana/wui/core/templates/core/site_settings.html
katana/wui/core/views.py
katana/wui/settings.py

Email settings integration in site settings page.

WAR-2136 - SMTP Settings integration in site settings page

---

katana/wui/core/views.py

…lected warriorspace in settings/general_settings in PIP mode.

WAR-2275 : Change the default browse options mode( in suites and projects) to selected warriorspace in settings/general_settings in PIP mode.

---

katana/primary_process.py

WAR-2295 Fix for develop branch.

---

warrior/WarriorCore/Classes/war_cli_class.py
warrior/WarriorCore/Classes/war_print_class.py

enabled backward compatibility warrior logging

WAR-2523: CLI option --nologger to support Backward Computability

---

release_notes.txt
version.txt

Release warrior 4.6.0
